# Generated by Django 5.0.6 on 2025-01-04 19:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Dbmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="faces/")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("point", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Face",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("date", models.CharField(default="15 Dey 1403", max_length=100)),
                ("time", models.TimeField(auto_now_add=django.utils.timezone.now)),
                ("verify", models.BooleanField(default=False)),
                ("noise", models.BooleanField(default=False)),
                ("point", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Getdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=50)),
                (
                    "date_time",
                    models.CharField(
                        default="15 Dey 1403", max_length=100, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("recognition", models.CharField(max_length=100, unique=True)),
                ("date", models.CharField(default="15 Dey 1403", max_length=100)),
                ("time", models.TimeField(auto_now_add=django.utils.timezone.now)),
                ("noise", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flag", models.BooleanField(default=False)),
                ("check_in_date", models.CharField(max_length=100)),
                (
                    "check_in_time",
                    models.TimeField(
                        auto_now_add=django.utils.timezone.now, unique=True
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("1", "humanities"),
                            ("2", "library"),
                            ("3", "administrative"),
                            ("4", "engineering"),
                            ("5", "sama"),
                            ("6", "medical sciences"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="verifi.result"
                    ),
                ),
            ],
        ),
    ]
