# Generated by Django 4.1 on 2024-02-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_in_time",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="face",
            name="date",
            field=models.CharField(default="15 Bahman 1402", max_length=100),
        ),
        migrations.AlterField(
            model_name="result",
            name="date",
            field=models.CharField(default="15 Bahman 1402", max_length=100),
        ),
    ]
