# Generated by Django 5.0.6 on 2025-02-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verifi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbmodel",
            name="personnelNumber",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="کد پرسنلی"
            ),
        ),
    ]
