# Generated by Django 5.0.6 on 2025-01-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verifi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="login_or_logout",
            field=models.BooleanField(default=False),
        ),
    ]
