# Generated by Django 4.1 on 2023-12-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="face",
            name="point",
            field=models.TextField(unique=True),
        ),
    ]
