# Generated by Django 4.1 on 2024-02-03 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("verifi", "0002_attendance_flag_alter_attendance_check_in_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="check_out_time",
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in_date",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=100, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_in_time",
            field=models.TimeField(auto_now_add=django.utils.timezone.now, unique=True),
        ),
    ]
