# Generated by Django 5.0.6 on 2025-01-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verifi", "0003_result_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="face",
            name="date",
            field=models.CharField(default="02 Bahman 1403", max_length=100),
        ),
        migrations.AlterField(
            model_name="getdate",
            name="date_time",
            field=models.CharField(
                default="02 Bahman 1403", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="date",
            field=models.CharField(default="02 Bahman 1403", max_length=100),
        ),
        migrations.AlterField(
            model_name="result",
            name="time",
            field=models.TimeField(auto_now_add=True),
        ),
    ]
