# Generated by Django 5.0.6 on 2025-02-13 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verifi", "0003_log_alter_getdate_date_time_alter_result_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
