# Generated by Django 5.0.6 on 2025-02-13 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verifi", "0004_log_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
