# Generated by Django 4.1 on 2023-12-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifi", "0005_face_verify"),
    ]

    operations = [
        migrations.AddField(
            model_name="face",
            name="noise",
            field=models.BooleanField(default=False),
        ),
    ]
